name:                tiger
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/tiger#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2021 Author name here
category:            Web
extra-source-files:
- README.md
- src/Lexer.x
  #- src/Parser.y

dependencies:
  - base >= 4.7 && < 5
  - array
  - megaparsec
  - template-haskell
  - text
  - containers

library:
  source-dirs: lib

executables:
  tiger:
    source-dirs:      src
    main:             Main.hs
    dependencies:
      - tiger

build-tools:
  - alex
    #- happy
